#!/bin/bash

echo "Git hook pre commit spotless"

cd ../Loteria-Mexicana || return

#./gradlew spotlessApply
#STATUS=$?
## return 1 exit code if running checks fails
#[ $STATUS -ne 0 ] && exit 1

./gradlew spotlessCheck
STATUS=$?

if [ $STATUS -ne 0 ]
then
  ./gradlew spotlessCheck
fi

# return 1 exit code if running checks fails
[ $STATUS -ne 0 ] && exit 1

exit 0
